name: Build app renygp
on:
  push:
    branches: [ "main" ]
    paths:
      - java-app/**
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        # Set the working directory to the java-app directory
        # works only for the shell.
        working-directory: java-app
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build JAR
        run: |
          mvn package
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4