name: Build app renygp
on:
  push:
    branches:
        - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Build JAR
        run: |
          mvn clean package -DskipTests
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4