  name: Greetings Workflow
  on:
    issues:
      types: [opened]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Greet the world
          run: echo "Hello, World!"